// import { Model, DataTypes, InferAttributes, InferCreationAttributes, CreationOptional } from "sequelize";
// import { sequelize } from "../config/example_connection"; // Import your database connection configuration

// /**
//  * Person model class representing a person with id and name.
//  * Validators are added to ensure the integrity of the data before saving to the database.
//  */
// export class Person extends Model<
//   InferAttributes<Person>, // Type for attributes that can be returned from queries
//   InferCreationAttributes<Person> // Type for attributes that are required when creating an instance
// > {
//   // Declaring the types of the attributes for TypeScript. These help with type-checking.
//   declare id: CreationOptional<number>; // id is optional on creation (auto-generated by Sequelize)
//   declare name: string; // name is a required string field
// }

// // Initialize the Person model and define its attributes, including validations
// Person.init(
//   {
//     // Define the id field with validation rules and configuration
//     id: {
//       type: DataTypes.INTEGER, // Define the field type as an integer
//       autoIncrement: true, // The ID will automatically increment when a new record is created
//       primaryKey: true, // This field will be the primary key for the table
//     },
    
//     // Define the name field and add validation rules
//     name: {
//       type: DataTypes.STRING, // Define the field type as a string
//       allowNull: false, // The name is required, cannot be NULL
      
//       // Add a custom validation to ensure the name is at least 3 characters long
//       validate: {
//         notEmpty: { // Ensures the field is not empty
//           msg: 'Name cannot be empty',
//         },
//         len: { // Ensures the name is at least 3 characters long
//           args: [3, Infinity], // Minimum length of 3, with no maximum limit
//           msg: 'Name must be at least 3 characters long',
//         },
//         isAlpha: { // Ensures the name contains only alphabetical characters
//           msg: 'Name must only contain letters',
//         },
//       },
//     },
//   },
//   {
//     sequelize, // The connection to your database
//     modelName: "Person", // The name of the model (used for table creation and associations)
//     //tableName: 'people', // Optional: specify the table name in the database
//     //timestamps: true, // Add timestamps (createdAt and updatedAt) to the model
//     //underscored: true, // Optional: use snake_case for column names (e.g., created_at, updated_at)
//   }
// );

// export default Person;
